resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/redhat-appstudio/application-service/config/default?ref=daa9c484120c4485af504b17059f86d518c3b887
- .tekton/


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/application-service
  newName: quay.io/redhat-appstudio/application-service
  newTag: daa9c484120c4485af504b17059f86d518c3b887

configMapGenerator:
- literals:
  - GITHUB_ORG=""
  name: github-config
  behavior: replace

namespace: application-service

patches:
  - ./manager_resources_patch.yaml
