resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/redhat-appstudio/release-service/config/default?ref=b8d8c619c8f434af649c0c9fa1b58c678c14b76f
- .tekton/


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/release-service
  newName: quay.io/redhat-appstudio/release-service
  newTag: b8d8c619c8f434af649c0c9fa1b58c678c14b76f

namespace: release-service

patches:
  - ./manager_resources_patch.yaml
